### PR TITLE
Improved cell and nucleus segmentation

### PR DESCRIPTION
**Pull request by Soorya19Pradeep**
This PR is based on issue #13 .  
The cell membrane segmentation is improved by finding membrane focus slice using nucleus channel. Then the membrane and nucleus channels are normalized and stacked for best segmentation with 'cyto2' model on cellpose.
The nucleus segmentation can be improved using retrained cellpose model.

### CODE REVIEW

**Comment by Soorya19Pradeep** [comment]
@nbathreya , I am planning on replacing the 'nuclei' segmentation model on cellpose which is currently used for nucleus channel segmentation with a model that I have retrained and found to work better with nucleus segmentation. I think the model is more sensitive at segmenting the nucleus in images we work with. This can improve the nuclear segmentation further. 

I would like to add the retrained model inside the PhenoSight folder structure just like the AICS workflows. Do you have suggestions on the idea and any suggestion for space in the folder structure for adding this model? Thanks!

**Comment by mattersoflight** [comment]
@Soorya19Pradeep how big is the model in MB? If it is too large, it can be shared publically on the cloud and we can add a link to the installation instructions to copy it to a specific folder. It is generally risky to version large files in git repositories. There is also a dedicated git extension (https://git-lfs.com/), which we can consider using.

**Comment by Soorya19Pradeep** [comment]
The model is 25 MB as we discussed earlier. Since it is big, I will move it to the large file storage on git or google drive and provide links for user to find the model if preferred. Thanks for the discussion @mattersoflight

**Comment by mattersoflight** [comment]
@Soorya19Pradeep Looking at this PR, I think we should merge this before #12. @nbathreya are you also able to test this PR? I can also take a look tomorrow morning for code architecture and we can merge it by the afternoon.

**Comment by Soorya19Pradeep** [comment]
@mattersoflight , @nbathreya and I are meeting tomorrow at 10 am to test the segmentation in this PR. Would you like to join?

**Comment by nbathreya** [comment]
The bug in the code has been identified and resolved. The code for calculating membrane segmentation needed to be tweaked:

# calculate the membrane segmentation if both nucleus and membrane channels are provided
            if membrane_channel != excluded_channel:
                mem_norm = cv2.normalize(
                    np.squeeze(image_data[membrane_channel]),
                    None,
                    0,
                    255,
                    cv2.NORM_MINMAX,
                )
                nucl_norm = cv2.normalize(
                    np.squeeze(image_data[nucleus_channel]),
                    None,
                    0,
                    255,
                    cv2.NORM_MINMAX,
                )
                mem_nucl_stack = np.stack((mem_norm, nucl_norm), axis=0)

                membrane_segmentation = calculate_membrane_segmentation(cyto_model, mem_nucl_stack, 0, 1, diameter)

The code is still running but I have checked some intermediate results which look great!

**Comment by nbathreya** [comment]
Code for max projections and cell object segmentation works well now. @Soorya19Pradeep if you can verify the results, we can go ahead and merge this branch.

**Comment by Soorya19Pradeep** [comment]
@nbathreya , thank you for testing the code and helping debug! I checked through the segmentation results for various FOVs. It looks great! I think we can merge this branch as well! Thanks again!

**Review by nbathreya — APPROVED** [review]

**Review by nbathreya — APPROVED** [review]

**Pull request merged**
